RADIANT_INSTALL_PATH=/opt/lscc/radiant
RADIANT_VERSION=2.2

build:
	$(RADIANT_INSTALL_PATH)/$(RADIANT_VERSION)/bin/lin64/radiantc < create_project.tcl

clean:
	rm -rf *.rdf *.sty .*.ini *.xml *.html *.log .recovery *.dir/ impl_1/
